### PR TITLE
index: add missing h5bp tags

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Allows media queries to work based on displayport width. And allows for most of
h5bp compat :sparkles: Thanks!

### CODE REVIEW

**Comment by mattdesl** [comment]
How'd you come up with the meta tag? It will affect all those using budo – since it changes the way apps look & feel. I use a different meta tag on my own apps, but it is a bit subjective and app-specific to assume one config over another.

The rest is 👍 !

**Comment by yoshuawuyts** [comment]
Haha, yeah so I copied what's on [h5bp/src/index.html](https://github.com/h5bp/html5-boilerplate/blob/3855f43e7269dd910a76bd18d8b3bb7a51c8084d/src/index.html#L8) - seems like a pretty solid standard. If it's too much happy to strip it out and put it into my own utils

**Comment by mattdesl** [comment]
I think it's best to avoid meta in this module since it's a very app-specific tag in practice.

**Comment by yoshuawuyts** [comment]
Alright, fair - just out of curiosity: what do you use? I never really gave it a thought until I tried making breakpoints work yest and they didn't haha - always just copied h5bp 😛

**Comment by yoshuawuyts** [comment]
Removed the meta tag, merged, released as `v1.2.1` :sparkles:

**Pull request merged**
