### PR TITLE
add base tag

### LINKED ISSUE #10: Adding <base href="/">
Would you consider adding `<base href="/">` (or a configurable base href) to make the budo built-in default work with pushstate?

This would fix https://github.com/mattdesl/budo/issues/159.

Thank you.

### PR DESCRIPTION
**Pull request by mantoni**
Fixes #10

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks for the PR! However, this should be disabled by default and only added if the user passes a string (the href). Then budo can opt into this feature without it breaking all the other tools depending on simple-html-index.

**Comment by mantoni** [comment]
Sure, that makes sense. Updated the PR. Do you think `base` is a good name for the option?

**Comment by mantoni** [comment]
Is anything preventing this from being merged? Can I do anything to help?

**Comment by mattdesl** [comment]
Looks good to me. I'm on vacation right now so I won't be able to merge for a couple weeks. 😊

**Comment by mantoni** [comment]
Fair enough. Will leave for hols end of the week as well :beers:

**Comment by yoshuawuyts** [comment]
Co-maintainer to the rescue! :tada:

**Comment by yoshuawuyts** [comment]
Released as `v1.4.0` :sparkles:

**Comment by mattdesl** [comment]
Heh thanks Yoshua! 👌

**Comment by mantoni** [comment]
Cool, Thanks! Will make a corresponding PR for budo then.

**Pull request merged**
