### PR TITLE
add lang option

### PR DESCRIPTION
**Pull request by tgfjt**
1. add html tags & toUpperCase(doctype) on test to fix test failure.
2. add lang option: default  `<html>`, optional `<html lang="xxx">` 

e.g.
`html({ title: 'こんにちは！😀', lang: 'ja' })`

### CODE REVIEW

**Comment by mattdesl** [comment]
Thanks! I think maybe the default should be `"en"` if no lang is passed, instead of removing the lang attribute altogether. Thoughts @yoshuawuyts ?

See here:
https://www.w3.org/TR/html5/semantics.html

**Comment by yoshuawuyts** [comment]
yup, defaulting to `en` sounds good

**Comment by tgfjt** [comment]
@mattdesl 
@yoshuawuyts 
Thank you!
Fixed it.

**Comment by mattdesl** [comment]
Thanks, it should be published as version `1.3.0`! :tada:

**Comment by tgfjt** [comment]
Yay! Thanks:smile:

**Pull request merged**
